-- =============================================================================
-- LexDraft - AI generation quota
-- =============================================================================
-- Tracks every AI document generated by a user against a per-plan monthly cap
-- anchored to the firm's billing cycle (firms.renews_at). Rows are append-only;
-- deleting an associated draft soft-tombstones the row via deleted_at but never
-- decrements the user's count against the cap. The cap itself lives in
-- plan_ai_caps and is set by migration only - no admin route mutates it.
--
-- Cycle bounds:
--   when firms.renews_at is not null:
--     cycle_end   = renews_at::timestamptz
--     cycle_start = (renews_at - interval '1 month')::timestamptz
--   when firms.renews_at is null (newly-provisioned / unconfigured firm):
--     cycle_end   = date_trunc('month', now()) + interval '1 month'
--     cycle_start = date_trunc('month', now())
--
-- Idempotent.
-- =============================================================================

create table if not exists ai_generations (
  id          uuid primary key default gen_random_uuid(),
  firm_id     uuid references firms(id) on delete cascade,
  user_id     uuid not null references users(id) on delete cascade,
  draft_id    uuid references drafts(id) on delete set null,
  kind        text not null check (kind in ('generate', 'stream')),
  provider    text,
  doc_type    text,
  created_at  timestamptz not null default now(),
  deleted_at  timestamptz
);

create index if not exists ai_generations_user_created_idx
  on ai_generations (user_id, created_at desc);

create index if not exists ai_generations_firm_created_idx
  on ai_generations (firm_id, created_at desc);

create index if not exists ai_generations_draft_idx
  on ai_generations (draft_id) where draft_id is not null;

create table if not exists plan_ai_caps (
  plan_tier      firm_plan_tier primary key,
  monthly_cap    integer not null check (monthly_cap >= 0),
  updated_at     timestamptz not null default now()
);

insert into plan_ai_caps (plan_tier, monthly_cap) values
  ('Solo', 20),
  ('Practice', 200),
  ('Firm', 1000)
on conflict (plan_tier) do nothing;
